site_name: OptiGUI documentation
repo_url: https://github.com/opekope2/OptiGUI-Next
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.expand
    - content.code.copy
nav:
  - Home: index.md
  - Resource packs:
    - Basic information & syntax: syntax.md
    - Replacing GUI textures: format.md
  - API docs:
    - 2.0.0-beta.1: kdoc/2.0.0-beta.1
  - API docs (Java syntax):
    - 2.0.0-beta.1: javadoc/2.0.0-beta.1
markdown_extensions: 
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
