name: Submit a resource pack
description: Add a supported resource pack to the README
body:
  - type: markdown
    attributes:
      value: |
        Please make sure that the resource pack contains OptiGUI(`/assets/optigui/gui`) or OptiFine (`/assets/minecraft/optifine/gui`) files.
  - type: input
    attributes:
      label: Homepage
      description: Enter the link to the resource pack homepage (Planet Minecraft or CurseForge page for example, NOT direct download)
    validations:
      required: true
