name: Publish Documentation

on:
  push:
    branches:
      - docs

jobs:
  deploy-docs:
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy documentation
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
